pipeline {
    agent {
        label 'build-poky'
    }
    environment { 
        LXC_IP  = '10.0.3.209'
        BUILD_TIME_CMD = "/usr/bin/time "
        BUILD_TIME_STR = "TIME: %e %S %U %P %c %w %R %F %M %x %C"
    }
    stages{
        stage('Install requirements') {
            steps {
                script {
                    if ( env.AGENT == "lxc" ) {
                        sh 'sudo lxc-attach -n build-poky -- apt-get install -y chrpath cpp diffstat g++ gawk gcc patch build-essential texinfo'
                    } else if ( env.AGENT == "docker") {
                        echo "Docker based...."
                        sh 'sudo docker rm -f build-poky || echo "build-poky had been destroyed"'
                    } else{
                        sh 'sudo apt-get install -y chrpath cpp diffstat g++ gawk gcc patch build-essential texinfo'
                    }
                }
            }
        }
        stage('Get code') {
            steps {
                script {
                    currentBuild.description = "${env.AGENT}"
                }
                sh 'rm -rf poky'
                dir('poky') {
                    git 'git://git.yoctoproject.org/poky'
                }
            }
        }
        stage('Prepare') {
            steps {
                dir('poky') {
                    sh "/bin/bash -c '. oe-init-build-env'"
                }
                dir('poky/build/conf') {
                    sh "/bin/bash -c 'cat ~/local.conf >> local.conf'"
                }
            }
        }
        stage('Build') {
            steps{
                script {
                    if ( env.AGENT == "lxc" ) {
                        sh "ssh ubuntu@${LXC_IP} 'pushd ${env.WORKSPACE}/poky && . oe-init-build-env && ${BUILD_TIME_CMD} -f \"${BUILD_TIME_STR}\" bitbake core-image-minimal '"
                    } else if ( env.AGENT == "docker" ) {
                        sh "sudo docker run --privileged=true --rm=true --name build-poky -u ubuntu -w ${env.WORKSPACE}/poky -v /home/ubuntu:/home/ubuntu -v /starfish:/starfish build-poky /bin/bash -c '. oe-init-build-env &&  ${BUILD_TIME_CMD} -f \"${BUILD_TIME_STR}\" bitbake core-image-minimal'"
                    } else {
                        dir('poky') {
                            sh "/bin/bash -c '. oe-init-build-env &&  ${BUILD_TIME_CMD} -f \"${BUILD_TIME_STR}\" bitbake core-image-minimal'"
                        } 
                    }
                }
            }
        }
    }
    post {
        always {
            build job: 'build-poky', parameters: [string(name: 'AGENT', value: "${env.AGENT}")], wait: false
        }
        success {
            archiveArtifacts allowEmptyArchive: true, artifacts: 'poky/build/tmp/buildstats/**/*, poky/build/tmp/log/**/*'
        }
    }
}
