pipeline {
    agent {
        label 'build-chrome'

    }
    environment { 
        LXC_IP  = '10.0.3.144'
        DOCKER_IP = '172.17.0.2'
        BUILD_TIME_CMD = "/usr/bin/time "
        BUILD_TIME_STR = "TIME: %e %S %U %P %c %w %R %F %M %x %C"
    }
    stages{
        stage('Install requirements') {
            steps {
                sh 'sudo apt-get install -y python'
            }
        }
        stage('Get code') {
            steps {
                /*
                dir('chromium') {
                    deleteDir()
                }
                dir('chromium') {
                    sh '''
                        fetch --nohooks chromium || gclient sync
                    '''
                }
                */
                echo "Pass"
                script {
                    currentBuild.description = "${env.AGENT}"
                }
            }
        }
        stage('Prepare') {
            steps {
                dir('chromium/src') {
                    //./build/install-build-deps.sh --no-prompt
                    /*
                    sh '''
                    gclient runhooks
                    '''
                    */
                    script {
                        if ( env.AGENT == "lxc") {
                            sh '''
                            ssh ubuntu@10.0.3.144 'pushd ~/jenkins_home/workspace/build-chrome/chromium/src && \
                            ./build/install-build-deps.sh --no-prompt && \
                            gclient runhooks && \
                            time rm -rf out && \
                            gn gen out/Default'
                            '''    
                        } else if ( env.AGENT == "docker") {
                            sh '''
                            ssh ubuntu@172.17.0.2 'pushd ~/jenkins_home/workspace/build-chrome/chromium/src && \
                            ./build/install-build-deps.sh --no-prompt && \
                            gclient runhooks && \
                            time rm -rf out && \
                            gn gen out/Default'
                            '''
                        } else {
                            sh './build/install-build-deps.sh --no-prompt'
                            sh 'gclient runhooks'
                            sh "/bin/bash -c 'time rm -rf out/'"
                            sh 'gn gen out/Default'
                        }
                    }
                }
            }
        }
        stage('Build') {
            steps{
                dir('chromium/src'){
                    script {
                        if (env.AGENT == "lxc") {
                            sh " ssh ubuntu@10.0.3.144 ' pushd ~/jenkins_home/workspace/build-chrome/chromium/src && ${BUILD_TIME_CMD} -f \"${BUILD_TIME_STR}\"  ninja -C out/Default chrome'"
                        } else if (env.AGENT == "docker") {
                            sh "ssh ubuntu@172.17.0.2 ' pushd ~/jenkins_home/workspace/build-chrome/chromium/src && ${BUILD_TIME_CMD} -f \"${BUILD_TIME_STR}\" ninja -C out/Default chrome'"
                        } else {
                            sh "/bin/bash -c '${BUILD_TIME_CMD}  -f \"${BUILD_TIME_STR}\" ninja -C out/Default chrome'"
                        }
                    }
                    
                }
            }
        }
    }
    post {
        always {
            build job: "${env.JOB_NAME}", parameters: [string(name: 'AGENT', value: "${env.AGENT}")], wait: false
        }
    }

}
